version: '3'

services:
  redis:
    image: redis:6
    command: redis-server --appendonly yes
    ports:
      - 6379:6379

  replicator:
    image: brechtvdv/ldes-replicator:0.0.4-alpha.0
    environment:
      URLS: https://lodi.ilabt.imec.be/odala/oslo
      STATE_CONFIG: '{"id":"replicator_0",
        "host":"redis",
        "port":6379}'
      POLL_INTERVAL: '5000'
      CONNECTORS: '[0]'
      CONNECTOR_0_TYPE: '@treecg/ldes-ngsild-connector'
      CONNECTOR_0_CONFIG: '{"amountOfVersions":0,
      "tokenEndpoint": "https://rc.obelisk.ilabt.imec.be/api/v3/auth/token",
        "clientId": "fill-in-or-empty",
        "clientSecret": "fill-in-or-empty",
        "ngsiEndpoint": "https://rc.obelisk.ilabt.imec.be/api/v3/ext/ngsi/fill-in-dataset-id/ngsi-ld/v1/"}'
